language: node_js
node_js:
  - "8"
addons:
  sonarcloud:
    organization: "duranda-github" # the key of the org you chose at step #3
    token: $SONAR_TOKEN
script:
  # other script steps might be done before running the actual analysis
  - npm test -- --coverage
  - sonar-scanner
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  local-dir: build
